# PERMISSIONS:
#
# krazybungee.staffchat.write                   Staffchat write
# krazybungee.staffchat.see                     Staffchat see
# krazybungee.trialstaffchat.write              Trialstaffchat write
# krazybungee.trialstaffchat.see                Trialstafftaffchat see
# krazybungee.staffconnectstatus.gain           Send status connection about this player
# krazybungee.staffconnectstatus.notification   See connection statuses
# krazybungee.admin                             Reload plugin

# FEATURES
staffchat:
  enabled: true
# Without slash symbol
  command: "staffchat"
  aliases: ["ac","sc"]
#   Placeholders:
#   {player} - player who sent message
#   {message} - message content
#   {server} - server message
  format: "&#64e386&lSC&#64e386 - {player} &8&l» &#64e386{message}"
  bypass servers:
    - "Auth"

trialstaffchat:
  enabled: true
  command: "trialstaffchat"
  aliases: ["tac","tsc"]
  #   Placeholders:
  #   {player} - player who sent message
  #   {message} - message content
  #   {server} - server message
  format: "&#47a18d&lTSC&#47a18d - {player} &8&l» &#47a18d{message}"
  bypass servers:
    - "Auth"

staff connect status:
  enabled: true
  #   {player} - player who sent message
  #   {from} - server name from you connect
  #   {to} - server name you are connecting to
  bungeecord connect: "&#64e386&l{player} &#64e386just connected to &f{to}&#64e386!"
  server change: "&#64e386&l{player} &#64e386switched server &f{from} &8&l» &f{to}&#64e386!"
  bungeecord disconnect: "&#64e386&l{player} &#64e386disconnected from server &f{from}&#64e386!"
  send yourself status: false
  #   Blacklist messaging to all of these servers
  bypass servers:
    - "Auth"

private bungee message:
  enabled: true
  command: "bungeemessage"
  aliases: ["bmsg"]
  #   {sender} - player who sent message
  #   {receiver} - player who receive message
  #   {message} - message
  sender format: "&#64e386BMSG &fyou &7⇒ &f{receiver} &8&l» &#64e386{message}"
  receiver format: "&#64e386BMSG &f{sender} &7⇒ &fyou &8&l» &#64e386{message}"
  bypass servers:
    - "Auth"

tab:
  enabled: true
  tab header:
    - ""
    - "&#64e386&lKrazyBungee"
    - ""
  tab footer:
    - ""
    - "&7&oMake your tab go kraaaazyyyyy..."
    - ""

redirect server commands:
  enabled: false
  commands:
    lol:
# Example of redirect command:
#
#    lobby:                     => Command, that could be registered
#      permission: ""           => Permission to see/execute command
#      aliases: ["hub","lob"]   => Aliases for commands
#      server: "Lobby"          => Server for redirect
#      message: ""              => Message sent when you redirect
#      denymessage: ""          => Message sent when you are on same server
#      clear chat before message: false

motd:
  enabled: true
  #Multiple motds, it will pick random one to show
  motd:
    - ""
    - ""
  custom player text:
    enabled: false
    text: ""
  player hover message:
    enabled: false
    text:
      - ""
      - ""
      - ""
      - ""

maintenance:
  # This enables feature of turning on maintenance, it won't turn on maintenance
  enabled: false
  broadcast change: true
  kick message:
    - ""
    - ""
    - ""
  motd:
    enabled: true
    #Multiple motds, it will pick random one to show
    motd:
      - ""
      - ""
    custom player text:
      enabled: false
      text: ""
    player hover message:
      enabled: false
      text:
        - ""
        - ""
        - ""
        - ""

message commands:
  enabled: true
  commands:

language:
  staffchat:
    no message: "&cYou didn't provide message to send through staffchat!"
  trialstaffchat:
    no message: "&cYou didn't provide message to send through staffchat!"
  maintenance:
    broadcast on: "&cMaintenance was deactivated!"
    broadcast off: "&cMaintenance was activated!"
    already on: "&cMaintenance is already on!"
    already off: "&cMaintenance is already off!"
  not enabled: "&cThis feature is not enabled on this server!"